### PR TITLE
gimjay23 catering page

### PR DESCRIPTION
**Pull request by gimjay23**
I have added a catering page to the Royale Rammy Foods website. Kindly merge changes if you may

### CODE REVIEW

**Comment by sintimmisa** [comment]
OK , will check it out

**Comment by gimjay23** [comment]
How did you find it? Did you get the chance to review it critically and interact with the site too please?

**Comment by sintimmisa** [comment]
yea, am making some additions. Kidly send me the woman's about content and
any other content to update

**Comment by gimjay23** [comment]
Please find attached her write up as requested.

Sent from my BlackBerry — the most secure mobile device

**Pull request merged**
